import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ padding: '2rem' }}>
        <h1>Welcome to Next.js!</h1>
        <p>
          Get started by editing <code>src/pages/index.tsx</code>.
        </p>
        <div>
          <a href="https://nextjs.org/docs" target="_blank" rel="noopener noreferrer">
            Documentation
          </a>
        </div>
      </main>
    </>
  );
}
